### ISSUE TITLE
Invoke-PageStackQuery shalle be Invoke-BookStackQuery

### ISSUE THREAD

**Issue by richardmeilinger** [My-Random-Thoughts/psBookStack#3]
Hi,

nice work with that PowerShell module.
I found an issue at the **Export-BsPage.ps1** cmdlet.

**Invoke-PageStackQuery** should be **Invoke-BookStackQuery.**

https://github.com/My-Random-Thoughts/psBookStack/blob/5aecc39e7ab16696d15d79557de499dcbbe6da05/public/Export-BsPage.ps1#L44

cheers 
Richard

**Comment by My-Random-Thoughts** [comment]
How did I miss that!?
Thank you, fixed now
