### ISSUE TITLE
Shelf ID's included in Get-BsBook, Get-BsChapter, and Get-BsPage

### ISSUE THREAD

**Issue by a70coupe** [My-Random-Thoughts/psBookStack#4]
Hello,

First, thanks for creating the BookStack PowerShell Module. I think this is a fantastic way to create exports/backups of anyone's BookStack instance.

I'm creating a PowerShell script to export pages into a directory that has the same structure as my BookStack instance. For example, **MyPage** located in
- Shelf
	- Book
		- Chapter
			- **MyPage**

Unfortunately, through the bs cmdlets I can't pull the Shelf information and the best I can do is
- Book
	- Chapter
		- **MyPage**

Is it possible to add the Shelf ID to the Get-BsBook, Get-BsChapter, and Get-BsPage cmdlets or am I missing something?

Example of a Get-BsBook
```
id          : 2
name        : Book
slug        : book
description :
created_at  : 2023-06-25T02:56:56.000000Z
updated_at  : 2023-06-25T02:56:56.000000Z
created_by  : 1
updated_by  : 1
owned_by    : 1
```

Exmple of a Get-BsChapter
```
id          : 1
book_id     : 2
slug        : chapter
name        : Chapter
description :
priority    : 3
created_at  : 2023-06-25T02:57:29.000000Z
updated_at  : 2023-07-14T11:29:01.000000Z
created_by  : 1
updated_by  : 1
owned_by    : 1
book_slug   : home-lab
```

Example of a Get-BsPage
```
id             : 2
book_id        : 2
chapter_id     : 1
name           : Page
slug           : page
priority       : 3
created_at     : 2023-06-25T02:57:37.000000Z
updated_at     : 2023-07-14T11:28:45.000000Z
created_by     : 1
updated_by     : 1
draft          : False
revision_count : 1
template       : False
owned_by       : 1
editor         :
book_slug      : home-lab
```

Thanks for any help/advice!

-a70coupe

**Comment by My-Random-Thoughts** [comment]
Bookstack allows books to be on multiple shelves, so the shelf information is not returned from the API for books.

You would need to use `Get-BsShelf -Id {shelf-id}` to get the details of a particular shelf and look at the `books` value returned to see what books it holds.

From your BookStack instance, goto `/api/docs#shelves-read` and see the returned data.

**Comment by a70coupe** [comment]
Thanks for the quick response! I'll take a look.
