### ISSUE TITLE
Unable to update page tags

### ISSUE THREAD

**Issue by shedtepherd** [My-Random-Thoughts/psBookStack#6]
I may be doing this incorrectly, please correct me if I am.

After authenticating with the Bookstack instance, I am attempting to add a tag to a page with the following:

```powershell
Update-BsPage -Id 1 -Tag @{ tag = 'value' }
```

But I am getting the following error:

```powershell
Update-BsPage: Parameter set cannot be resolved using the specified named parameters. One or more parameters issued cannot be used together or an insufficient number of parameters were provided.
```

The only way I can get the page to update is to fully populate all of the parameters, which would update the title and body of the page.

```powershell
Update-BsPage -Id 1 -Tag @{ tag = 'value' } -BookId 1 -Name 'test' -Html '<h1>hello</h1>'
```

Can you tell me what I'm doing incorrectly?

**Comment by My-Random-Thoughts** [comment]
Hi, thanks for reporting this.

It's most likely the way I have the parameter sets done.
I'll have a look at it this weekend.

**Comment by shedtepherd** [comment]
The function is working now. It's not updating the tags of the page but overwriting the tags that are already there. I apologize, I would attempt to submit a PR, but I am not well versed in APIs. I'll poke at it and try to come up with a PR for this.

**Comment by My-Random-Thoughts** [comment]
Ah OK.  Let me have a look

**Comment by shedtepherd** [comment]
Works flawlessly, thank you @My-Random-Thoughts
